// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLG1XYaYgHRVgZNMNgSWyoyuQCXacWNTE',
    appId: '1:710035774601:web:2681fb370a5b19ae19ba58',
    messagingSenderId: '710035774601',
    projectId: 'posinventory-a9f32',
    authDomain: 'posinventory-a9f32.firebaseapp.com',
    storageBucket: 'posinventory-a9f32.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5DZQgq_iwENVqy1-peFxIzd27RzE-3nc',
    appId: '1:710035774601:android:45f59f35be75c24219ba58',
    messagingSenderId: '710035774601',
    projectId: 'posinventory-a9f32',
    storageBucket: 'posinventory-a9f32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZiipUT6ENz49FTHJbjtwjhqSfwdBlWj8',
    appId: '1:710035774601:ios:a858fe3993e6d53b19ba58',
    messagingSenderId: '710035774601',
    projectId: 'posinventory-a9f32',
    storageBucket: 'posinventory-a9f32.appspot.com',
    iosClientId: '710035774601-tkotst8hsfj50afr65qg1dl2t5jdj75f.apps.googleusercontent.com',
    iosBundleId: 'com.symbex.pos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZiipUT6ENz49FTHJbjtwjhqSfwdBlWj8',
    appId: '1:710035774601:ios:a858fe3993e6d53b19ba58',
    messagingSenderId: '710035774601',
    projectId: 'posinventory-a9f32',
    storageBucket: 'posinventory-a9f32.appspot.com',
    iosClientId: '710035774601-tkotst8hsfj50afr65qg1dl2t5jdj75f.apps.googleusercontent.com',
    iosBundleId: 'com.symbex.pos',
  );
}
